# Generated by Django 2.2 on 2021-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20210112_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('hb', 'hobbit'), ('lotr', 'lords of the ring')], max_length=500),
        ),
    ]
